name: scicomp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyter
  - numpy
  - sympy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - statsmodels
  - scikit-learn
